# Generated by Django 3.2.6 on 2021-08-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-income_date']},
        ),
        migrations.RenameField(
            model_name='income',
            old_name='expense_date',
            new_name='income_date',
        ),
    ]
