# Generated by Django 3.2.6 on 2021-08-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_app', '0002_auto_20210817_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='category',
            new_name='source',
        ),
    ]
